import { NextRequest, NextResponse } from "next/server"
import { supabase } from "@/lib/supabase"

/**
 * POST /api/agent/daily-summary-all
 *
 * Triggers a daily PDF report for every agent in Supabase.
 * Accepts an optional `date` (YYYY-MM-DD); defaults to today.
 *
 * Each report is generated by calling /api/agent/daily-summary internally,
 * so Box credentials and Bedrock credentials must be configured.
 *
 * Can be wired to a Vercel Cron Job:
 *   vercel.json → { "crons": [{ "path": "/api/agent/daily-summary-all", "schedule": "0 23 * * *" }] }
 * or called from any scheduler at the URL:
 *   POST https://your-domain/api/agent/daily-summary-all
 *   Authorization: Bearer <CRON_SECRET>
 */

const CRON_SECRET = process.env.CRON_SECRET

function getBaseUrl(req: NextRequest): string {
  const host = req.headers.get("host") ?? "localhost:3000"
  const proto = host.startsWith("localhost") ? "http" : "https"
  return `${proto}://${host}`
}

export async function POST(req: NextRequest) {
  // Optional secret check so the cron endpoint can't be abused
  if (CRON_SECRET) {
    const auth = req.headers.get("authorization") ?? ""
    if (auth !== `Bearer ${CRON_SECRET}`) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }
  }

  let date: string | undefined
  try {
    const body = await req.json()
    date = body.date
  } catch {
    // no body – use today
  }

  const reportDate = date ?? new Date().toISOString().slice(0, 10)

  /* Fetch all agents */
  const { data: agents, error } = await supabase
    .from("agents")
    .select("id, name")
    .order("created_at", { ascending: true })

  if (error || !agents?.length) {
    return NextResponse.json({ error: error?.message ?? "No agents found" }, { status: 500 })
  }

  const baseUrl = getBaseUrl(req)

  /* Fire all PDF jobs in parallel (Box upload rate-limits are generous) */
  const results = await Promise.allSettled(
    agents.map(async (agent) => {
      const res = await fetch(`${baseUrl}/api/agent/daily-summary`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ agent_id: agent.id, date: reportDate }),
      })
      const json = await res.json()
      return { agent: agent.name, ...json }
    })
  )

  const succeeded = results
    .filter((r): r is PromiseFulfilledResult<Record<string, unknown>> => r.status === "fulfilled" && r.value.success)
    .map((r) => r.value)

  const failed = results
    .filter((r) => r.status === "rejected" || (r.status === "fulfilled" && !r.value.success))
    .map((r) =>
      r.status === "rejected"
        ? { error: r.reason?.message ?? "Unknown" }
        : r.value
    )

  return NextResponse.json({
    date: reportDate,
    total: agents.length,
    succeeded: succeeded.length,
    failed: failed.length,
    reports: succeeded,
    errors: failed,
  })
}

/** GET is also supported so Vercel Cron (which sends GET) works out of the box. */
export async function GET(req: NextRequest) {
  return POST(req)
}
